source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :osx, '10.14'
inhibit_all_warnings!
use_frameworks!

project 'SpotlightLyricsMacExample'

target 'SpotlightLyricsMacExample' do
    pod 'SpotlightLyrics', :path => '../../SpotlightLyrics.podspec'
    pod 'SpotlightLyrics/Mac', :path => '../../SpotlightLyrics.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
